# Generated by Django 4.0.3 on 2022-03-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='img',
            field=models.ImageField(default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='img',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
