# Generated by Django 4.0.3 on 2022-03-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_subtopic_img_alter_wikipage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtopic',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='img',
            field=models.ImageField(blank=True, default=None, upload_to='images'),
        ),
    ]
