# Generated by Django 4.0.3 on 2022-03-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_edit_edited_by_subtopic_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikipage',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
